name: lovetile
description: Una App per farsi perdonare i momenti brutti

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.1
  intl: ^0.16.0
  flutter_rounded_progress_bar: ^0.1.2
  font_awesome_flutter: ^8.5.0
  dotted_border: ^1.0.4
  flutter_staggered_grid_view: ^0.3.0
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  path_provider:

dev_dependencies:
  json_serializable: ^3.2.5
  build_runner: ^1.7.2
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
